FROM node:18.12.1

WORKDIR /producer

COPY package*.json ./
COPY prisma ./prisma/
COPY .env ./
RUN npm install
RUN npx prisma migrate dev --name init

COPY . .

EXPOSE 3000

CMD ["npm","start"]
