version: "3.8"
services:
  postgres:
    image: postgres:15.3-alpine
    container_name: bd-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - 5432:5432
    networks:
      - microservices
    #volumes:
      #- ./data/postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bd-pgadmin
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - 8080:80
    networks:
      - microservices
    #volumes:
      #- ./data/pgadmin:/var/lib/pgadmin
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    restart: always
    ports:
      - 15672:15672
    #volumes:
      #- ./dados:/var/lib/rabbitmq/
    networks:
      - microservices
networks:
  microservices:
   driver: bridge