FROM node:18.12.1

WORKDIR /consumer

COPY package*.json ./
COPY prisma ./prisma/
COPY .env ./
RUN npm install
RUN npx prisma migrate dev --name init

COPY . .

EXPOSE 3001

CMD ["npm","start"]